### PR TITLE
Example showing exception handling and reconnects

### PR DESCRIPTION
**Pull request by andrevdm**
As proposed in https://github.com/hreinhardt/amqp/issues/105

I've added a new example in examples/connectionManagement that should demonstrate a way to handle connection and channel errors.

I've done the following to make this work. If any of this is a problem I'm happy to discuss options :)

- Added this new example and the existing examples as executables in the cabal project.
I think this was necessary because this new example needs a couple of additional imports (e.g. safe-exceptions) and making sure it builds seems like a good idea for anyone wanting to use it.
_Perhaps you would want a cabal flag so these are only build when the user actually wants them? I think you'd need to require a later version of cabal for this to work. I'm happy to add that this this PR if you want that._

   - The existing examples were moved into their own directories in `examples/` to make this work
   - I fixed a few simple hlint warnings that adding the examples revealed.

- Added a Makefile. Mostly so that there is an easy way to build all the examples `make build-examples`

- I've added comments to the new example, hopefully they explain the idea well.

Let me know what you think

Andre

### CODE REVIEW

**Comment by hreinhardt** [comment]
I'm a bit skeptical of adding the examples into the main cabal-file. I don't think anybody would want to install these directly as executable binaries.

What about giving each example its own .cabal file? So users could just duplicate the whole example from its directory and go from there. 

Not sure if there's any drawbacks with that approach.

**Comment by andrevdm** [comment]
Yeah agreed. Having a bunch of examples when you do a `cabal install` seems like a bad idea.

Separate cabal files seems like a good idea to me. I'll do that in a bit and update the PR

**Comment by andrevdm** [comment]
Ok pushed. 

- Each example has its own cabal file. 
- The version for the example cabal files matches the main amqp version number. I think that makes sense, but may be a pain when updating the main package?
- You can use the make file to build all the examples `make build-examples` or to run individual ones e.g. `make run-example-consumer`

Hopefully that is a bit better.

Let me know if there are any issues

**Comment by hreinhardt** [comment]
Thanks.

I'd suggest keeping the /examples .cabal files as minimal as possible, e.g. no need for Description, Maintainer, Homepage, source-repository etc. Just the minimal stuff so it can be executed.

> The version for the example cabal files matches the main amqp version number. I think that makes sense, but may be a pain when updating the main package?

I would say just set it to 1.0 for all the examples, since there's really no meaningful value to put there.


I haven't yet taken a close look at your new contributed example but will do so in the next 1-2 days.

**Comment by andrevdm** [comment]
> I'd suggest keeping the /examples .cabal files as minimal as possible, e.g. no need for Description, Maintainer, Homepage, source-repository etc. Just the minimal stuff so it can be executed.
> I would say just set it to 1.0 for all the examples, since there's really no meaningful value to put there.

Good points and easy to do too :). I've updated them
 
> I haven't yet taken a close look at your new contributed example but will do so in the next 1-2 days.

Great, thanks. It is a bit of code to go though, hopefully it all make sense and the comments explain the intent well enough

**Comment by hreinhardt** [comment]
Consider this code from `ExampleConnectionManagement.hs`:

```haskell
let runConsumer =
        -- The call to `consumeMsgs` that we want to keep running
        Cm.withChannel cm $ \chan -> do
         void $ consumeMsgs chan "myQueueEN" Ack myCallbackEN
```

The problem is that `consumeMsgs` will return immediately, but the subscription will stay alive in the background and is tied to that specific channel.

So once the resource-pool closes the channel, the subscription will implicitly be cancelled. I think that's not what the user would expect to happen.

You can easily trigger it in your example by changing the function to something like this:

```haskell
let runConsumer =
        -- we force the consumer to be on channel 2, which will be closed after 60 seconds by the resource-pool.
        -- (we can't use channel 1 since that one will be kept open because we constantly call publishMsg on it)
        Cm.withChannel cm $ \_ -> do
        Cm.withChannel cm $ \chan -> do
         void $ consumeMsgs chan "myQueueEN" Ack myCallbackEN
```

In addition to this problem, some methods like `cancelConsumer` will only work if they're executed on the same channel that the subscription was created on.

So my conclusion is that using a resource-pool for channels doesn't really fit the semantics of AMQP. I think we need to make users open/close the channels by themselves, so that they have full control.

This would make your code slightly less useful since users would now have to manually do `addChannelExceptionHandler` but I unfortunately don't see a way around that.

**Comment by andrevdm** [comment]
> So my conclusion is that using a resource-pool for channels doesn't really fit the semantics of AMQP. I think we need to make users open/close the channels by themselves, so that they have full control.

Oh right I see! Thanks, I definitely misunderstood that.

I'll think about it a bit. Feels like there may be a way, but I'm not sure how general a solution it would be. I'll want to do this for myself anyway, so I'm happy to try and then update the PR if you are interested. Also happy to close for now if that makes more sense.

Thanks again for taking the time to look

**Comment by hreinhardt** [comment]
Sounds good to me :)

**Comment by hreinhardt** [comment]
Yeah, wouldn't make a good example, but it definitely looks interesting. Good luck with that approach!

**Pull request closed without merging**
