### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by peterbecich**
modified from https://github.com/jgm/pandoc/blob/master/.github/workflows/ci.yml

https://github.com/peterbecich/amqp/actions/runs/954025604

### CODE REVIEW

**Comment by hreinhardt** [comment]
It seems that the tests are all failing because there's no RabbitMQ instance running. I'm not familiar with Github Actions but it doesn't seem very useful to me to run the tests if they're going to fail anyway.

**Comment by peterbecich** [comment]
There is now a running RabbitMQ instance. There is one failing test remaining:

```
  1) ConnectionSpec.openConnection, with custom vhost and valid credentials, connects successfully
       uncaught exception: AMQPException
       ConnectionClosedException Abnormal "Handshake failed. Please check the RabbitMQ logs for more information"
 ```

https://github.com/hreinhardt/amqp/blob/1c1509e576e5348bfbf08fed0e400953456de74c/test/ConnectionSpec.hs#L19-L25

**Comment by hreinhardt** [comment]
Great. Maybe it's possible to execute the `bin/ci/before_build.sh` script somehow, hoping that it fixes the test? If not, we can probably just comment out the failing test.

**Comment by peterbecich** [comment]
Yes, very good. Done:
https://github.com/hreinhardt/amqp/blob/ad642bfbff685517db258d8ee2c3a4494831235d/.github/workflows/ci.yml#L67

All tests succeed now: https://github.com/peterbecich/amqp/actions/runs/1002264695

**Comment by hreinhardt** [comment]
Perfect. Thanks for contributing.

**Pull request merged**
