### PR TITLE
Add Consumer Cancellation Notification support

### PR DESCRIPTION
**Pull request by nikomi**
- clients now signal capabilty consumer_cancel_notify to the server
- new function addConsumerCancellationListener to register listeners
- listeners have type ConsumerTag -> IO ()

### CODE REVIEW

**Comment by hreinhardt** [comment]
After a first look, the patch looks fine to me. You still have `deliveryTag` in line 588, but I can also fix that later.

I'll wait until you have tested it before merging.

BTW I think you can update the commits in a pull-request without having to create a new one.

**Comment by nikomi** [comment]
Ok, fixed that one too - the commit automatically showed up in this thread, I hope it will be included in the merge as well...

I'll have to test if it is ok to always set this capability even for older versions of RabbitMQ - if not I'd suggest to check the server `capabilities` in the `server-properties` field of `connection.start` for `consumer_cancel_notify`.

**Comment by nikomi** [comment]
Btw, I'm not entirely happy with the interface - it forces the client to keep the ConsumerTag and match from ConsumerTag to Queue Name or whatever the client would prefer. And since all callbacks will be called for every cancellation currying the information won't really help.

I'm thinking of keeping a map from ConsumerTag to (QueueName, RoutingKey) and calling the callback with this tuple (or ConsumerTag + Q/R tuple) - what do you think?

**Comment by hreinhardt** [comment]
As a general principle I'd like to give people a reasonably direct interface to AMQP, so that they have maximum freedom in building their application.
But I'm also not opposed to providing users with optional extra information, so I'd be open to your proposal. 
On the other hand, even with the simple (ConsumerTag only) variant, it would be pretty easy for users to implement this mapping themselves, wouldn't it? 

> I'm thinking of keeping a map from ConsumerTag to (QueueName, RoutingKey)

Is it actually possible to know the RoutingKey of a consumer?

**Comment by nikomi** [comment]
Stumbled upon the `isResponse` declarations - I think `Basic.cancel` must be declared as 'not a response' as well, see commit above.

**Comment by hreinhardt** [comment]
Also, if we do decide to store the mapping between consumer-options and resulting consumer-tag, it would probably be a good idea to make that generally available, something like:
```haskell
getConsumerOpts :: Channel -> ConsumerTag -> IO ConsumerOpts
```
(where `ConsumerOpts` is a type we'd have to define, that would store the queue-name and maybe other consumer-options).

If we decide to do that, it wouldn't be necessary to pass the information into addConsumerCancellationListener anymore.

**Comment by hreinhardt** [comment]
> Stumbled upon the isResponse declarations - I think Basic.cancel must be declared as 'not a response' as well, see commit above.

Good catch.

**Comment by nikomi** [comment]
No, it's not possible to know the routing key, my bad.

Please take a look at this variant: users can declare a cancellation notification callback together with the consumer callback and can pass any information they like to the callback using a partially applied function. The two callbacks are kept together in the consumerTag lookup map.

Note: If you prefer the global callback to the queue-specific callbacks I can roll back this commit - but I find the queue-specific variant easier to use as the users can pass any information they like to the partially applied callback function instead of having to code a lookup. If you dislike the API extension on `consumeMsg''` we could achieve the same effect with an `addConsumerCancellationListener` function requiring the consumerTag as a parameter.

**Comment by nikomi** [comment]
Ah - the joys of asynchronous communication!

**Comment by michaelklishin** [comment]
Please keep in mind that as far as the protocol goes, consumers (and thus their tags) are channel-scoped state. It is perfectly possible to have more than one consumer per queue (sometimes doing so makes sense), or share a consumer (function) for N queues — of course, to RabbitMQ that'd be multiple consumers each with its own tag.

So I'd warn against making the same mistake some other clients made: instead of presenting the protocol more or less as is and carefully adding convenience features, introducing client-specific abstractions that may even lead some users to believe that the protocol works the way this client API presents it.

**Comment by nikomi** [comment]
Yes, we definitely have to keep that in mind!

Do you feel the queue-specific variant violates that approach?

**Comment by hreinhardt** [comment]
I'm leaning slightly against your new proposal, mostly because we'd put something into the library that users could easily implement themselves. 

Also Michael has a point: if every client library presents AMQP features in slightly different ways, this might lead to confusion.

So might be best to go back to your original idea: Let's just give users the ConsumerTag and have them implement their own logic to match it up with the queue-name.

**Comment by nikomi** [comment]
Okidok, here is the revert. I'll try to test this on Monday.

**Comment by nikomi** [comment]
Successfully tested with RabbitMQ 3.4.4, 3.5.7, 3.6.12 - couldn't find older versions as Docker images.

When deleting a queue in the management interface the associated Consumer Cancellation Notification with the correct ConsumerTag is received, when deleting another queue another notification with the correct tag is received.

When multiple consumers are listening on the same queue every consumer is notified separately.

**Comment by michaelklishin** [comment]
@nikomi in other clients the cancellation handler is associated with the consumer, either as a consumer interface method or as an optional function provided when registering a consumer. No associating with the queue per se (unless you already believe that a queue can only have one consumer). So I vote for the original channel-oriented interface.

**Comment by nikomi** [comment]
I don't quite get it:
- you write 'in other clients the cancellation handler is associated with the consumer, either as a consumer interface method or as an optional function provided when registering a consumer' - I provided this variant as @consumeMsgs''@ and it was voted down, and you vote for the variant that differs from other clients (maybe my incorrect commit description confused matters)
- you write 'unless you believe that a queue can only have one consumer' - in my comment above concerning test results I stated 'multiple consumers listening on the same queue...'

I'm not sure what you are trying to tell me and why it is a good idea for the Haskell client to differ from other clients...

**Comment by hreinhardt** [comment]
I think @michaelklishin might have been confused by your use of the term "queue-specific" when (I think) you really meant "consumer-specific".

Basically there are 2 proposals:

1. global callback:
```haskell
addConsumerCancellationListener :: Channel -> (ConsumerTag -> IO ()) -> IO ()
```

2. consumer specific callback:
```haskell
consumeMsgs'' :: Channel 
              -> Text 
              -> Ack 
              -> ((Message,Envelope) -> IO ()) 
              -> IO () -- this would be called when consumer is canceled
              -> FieldTable 
              -> IO 
```

I have a slight preference for option 1 just because it is more primitive, but it sounds to me like both of you are preferring option 2.

**Comment by nikomi** [comment]
Yes, my commit description was definitely incorrect and misleading. And yes, I would prefer the consumer specific variant - to me it feels easier to use and more in line with other RabbitMQ clients. 

Thanks for the concise presentation of the two options! Let's see how @michaelklishin will weigh in on them.

**Comment by nikomi** [comment]
I reviewed the code for per-consumer cancellation notifications and noticed an API divergence compared to Java: `public void handleCancel(String consumerTag) throws IOException { }`

I amended the interface accordingly:
```
consumeMsgs'' :: Channel 
              -> Text 
              -> Ack 
              -> ((Message,Envelope) -> IO ()) 
              -> (ConsumerTag -> IO ()) -- this would be called when consumer is canceled
              -> FieldTable 
              -> IO 
```
I retested this against RabbitMQ 3.4.4, 3.5.7, and 3.6.12 - all notifications are sent out correctly when e.g. deleting a queue using the management console.

If I can convince you to go with this variant I will gladly push the change :-)

**Comment by hreinhardt** [comment]
OK let's use that variant. I checked the Clojure AMQP library, and this implementation looks very similar, so we're not inventing anything new here.

Only thing I'm left wondering is whether we should add a new function `consumeMsgs''` or just change the existing `consumeMsgs'`. It just feels a bit inelegant to have three different consume-functions.

**Comment by nikomi** [comment]
I agree wholeheartedly - I will make this `consumeMsgs'` and push the commit.

**Comment by nikomi** [comment]
The API change is now included in the `Lifted` module which I forgot before.

I also retested with RabbitMQ 3.6.12 for sanity reasons.

**Comment by hreinhardt** [comment]
Thanks! (I took the liberty of squashing your commits to make them easier to look at, but this seems to make Github not understand the relation between this pull-request and the commit)

**Comment by nikomi** [comment]
Thanks!

I also considered squashing them but found the same problem... could have created a new pull request though...

btw please don't release right away, I'm currently preparing one more pull request to handle this: https://www.rabbitmq.com/connection-blocked.html - I just need to rebase it to the current master to remove the merge conflicts.

**Comment by hreinhardt** [comment]
Too late, already released it ;) But not a big deal to make another release when your changes landed.

**Pull request closed without merging**
