### PR TITLE
Fix heartbeats validation logic

### PR DESCRIPTION
**Pull request by kuznero**
With regards to a discussion [here](https://github.com/hreinhardt/amqp/issues/25#issuecomment-69451912).
Only checks heartbeats if `lastFrameTime` is present, otherwise skipping running cleanup action.
Also added `before_build.bat` file to prep for run on Windows.

### CODE REVIEW

**Comment by hreinhardt** [comment]
Have you really observed lastFrameTime to be zero? It should be initialized to the current timestamp: https://github.com/hreinhardt/amqp/blob/master/Network/AMQP/Internal.hs#L244

**Comment by kuznero** [comment]
I have not yet looked through this, but I observed it was `0` at the time of execution which was exactly the reason for so many failing tests. I will try to figure out why exactly it stays `0` long enough to provoke failure and get back to you later.

**Comment by kuznero** [comment]
You were right - value cannot turn 0 as it is set initially. I overlooked it in the beginning. But I have looked into it a bit more carefully and found out that System.Clock does not give you comparable values meaning that you cannot reliably test for greater then/less then/etc. I will post another pull request where I changed it for old-time package (as soon as I ger off the train in a few hours hopefully).

**Comment by hreinhardt** [comment]
System.Clock should give monotonically increasing timestamps. If it doesn't, then either the `clock` library is buggy or there is a bug somewhere in the AMQP library. 
If the bug is in AMQP, then it might be in the `getTimestamp` function in Helpers.hs. 

I believe that using old-time is problematic, since the user may change the local time while the application is running.

**Comment by fegu** [comment]
I agree with hreinhardt, the choice of System.Clock was made due to the need for a monotonic clock. I am eager to see this bug solved, as I experience the same problem and had to disable heartbeats. Let me know if I can help.

**Comment by kuznero** [comment]
I see. I agree, but I'd say that if it would be possible to get time stamps in UTC that should solve the problem as well. I suspect problem is in Clock package in the end as sometimes it returns negative values for seconds and sometimes positive which makes it impossible to compare.

**Comment by kuznero** [comment]
And Travis CI cannot satisfy old-time package :( I will try finding a better approach with UTC and pull another request later today or tomorrow.

**Comment by hreinhardt** [comment]
Could you try running this and see if it returns monotonic timestamps:
```haskell
import Data.Int
import System.Clock


getTimestamp :: IO Int64
getTimestamp = fmap us $ getTime Monotonic
  where
  	seconds spec = (fromIntegral . sec) spec * 1000 * 1000
  	micros spec = (fromIntegral . nsec) spec `div` 1000
  	us spec = (seconds spec) + (micros spec)
    
    
main = go
  where
    go = do
        print =<< getTimestamp
        go
    
```

**Comment by kuznero** [comment]
That is what I get:

```plain
5398196081187696768
6313936435008843935
-4298155896244457344
-2437382274692861824
-1114603266024853376
-7387093076992774016
8449223200521924736
4613384472490487936
378556889117044864
-7389845704352911232
-7700159221792690048
3660660670679560320
5388009380834259072
5220996588232061087
707617354688311424
-6619618567642337152
```

**Comment by hreinhardt** [comment]
Interesting. And this program:
```haskell
import Data.Int
import System.Clock

main = go
  where
    go = do
        print =<< (fmap sec) (getTime Monotonic)
        go
```

**Comment by kuznero** [comment]
This is way better:

```plain
1316474555023488962
1328738189892122562
1342608181184165826
1355660006976124866
1368367990571268034
1380996624645617602
1393279659881527234
1405308780945864642
1417822803817920450
1432294073351534530
1445673867141183426
1458142045532321730
1470470925249148866
1482711637877323714
1494996434049824706
1507226568173549506
1520703346619709378
1533162707442988994
1534363502989539266
```

**Comment by hreinhardt** [comment]
Ok but there is something wrong here. These numbers should reflect the current number of seconds. So they should increment by one. When I run it it looks like this:
```
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6450
6450
6450
6450
6450
```
So there probably is some bug in the clock library. Which version of clock do you run?

**Comment by kuznero** [comment]
Ah! One thing to notice :) I'm running Haskell Platform 2014.2.0.0, **x64**. It might have something to do with the sizes of primitive structures somehow.

And, I am using `clock-0.4.1.3`.

**Comment by hreinhardt** [comment]
I'm running 32-bit GHC, so this may be the reason I can't reproduce it. 
I would suggest you open a bug-report on the `clock` project and maybe they have some idea what the cause is.

**Comment by kuznero** [comment]
Will do that... Meanwhile, do you think it is possible to do something with **amqp** such that we could start using it in our projects?

**Comment by hreinhardt** [comment]
Well you could disable heartbeats or use a 32-bit GHC.

**Comment by hreinhardt** [comment]
Seems the issue has already been reported: https://github.com/corsis/clock/issues/17

**Comment by cetinsert** [comment]
`clock-0.4.3.0` finally uploaded to hackage. Please confirm it fixes your issues.

**Comment by hreinhardt** [comment]
After some (limited) testing, I think it fixes the issues. Thanks @cetinsert

**Pull request closed without merging**
